version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5001:5000"  
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
      - REDIS_HOST=redis
    depends_on:
      - redis

  frontend:
    build:
      context: ./myapp
    ports:
      - "3001:3001"  
    #volumes:
    #  - ./myapp:/app
    #  - /app/node_modules
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true

  redis:
    image: redis:7
    ports:
      - "6380:6379"  
    volumes:
      - redis-data:/data

volumes:
  redis-data:
